version: "4"
name: ipfs-ollama-anythingllm
services:
  ipfs-ollama:
    image: rockyburrisjr/myollama:latest
    pull_policy: always
    container_name: ipfs-ollama
    ports:
      - 11434:11434
    restart: on-failure

  ipfs-anythingllm:
    image: rockyburrisjr/ipfs-llm:latest
    pull_policy: always
    container_name: ipfs-anythingllm
    ports:
      - 3001:3001
    restart: on-failure
